---
# 002_mkdir/tasks/main.yml

- name: Create directory [java]
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - C:\Java\jdk1.8.0_201
    - C:\Java\jre1.8.0_201

- name: Create directory [log]
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - C:\imart\log

- name: Create directory [IM/Biz]
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - C:\imart\biz_batch_bootstrap
    - C:\imart\biz_di_manager
    - C:\imart\biz_asynchronous_manager
    