# 003_install_java/tasks/main.yml
---
# ansible マネジャの/root/git/soft/ に下記があること
# ・jdk-8u201-windows-x64.exe
# 
# JDK 
# 


- name: copy jdk-8u201-windows-x64.exe
  win_copy:
    src: /root/git/soft/jdk-8u201-windows-x64.exe
    dest: C:\Java\jdk-8u201-windows-x64.exe
- name: install java
  win_shell: C:\Java\jdk-8u201-windows-x64.exe /s INSTALLDIR=C:\Java\jdk1.8.0_201 /INSTALLDIRPUBJRE=C:\Java\jre1.8.0_201
- name: delete jdk-8u201-windows-x64.exe
  win_file:
    path: C:\Java\jdk-8u201-windows-x64.exe
    state: absent
